parameters:
- name: 'projectName'
  type: string
  default: false
- name: 'status'
  type: string
  default: false

steps:
- script: 'npm install duststream-azure-pipelines'
- script: 'node updateJobStatus.js ${{parameters.projectName}} ${{parameters.status}}'
  workingDirectory: node_modules\duststream-azure-pipelines
  env:
    MAPPED_API_KEY: $(WaterfallsApiKey)
  condition: always()
